name: Saga Checker

on:
  schedule:
    - cron: '*/1 * * * *'  # jede Minute
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
      TWILIO_TO: ${{ secrets.TWILIO_TO }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install requests twilio beautifulsoup4

      - name: Download hash artifact
        uses: actions/download-artifact@v4
        with:
          name: saga-hash
        continue-on-error: true

      - name: Run Saga Checker
        run: python saga_checker.py

      - name: Upload hash artifact
        uses: actions/upload-artifact@v4
        with:
          name: saga-hash
          path: saga_hash.txt
