name: Saga Checker

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
      TWILIO_TO: ${{ secrets.TWILIO_TO }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install requests twilio

      - name: Cache saga_hash.txt
        uses: actions/cache@v4
        with:
          path: saga_hash.txt
          key: saga-hash

      - name: Run Saga Checker
        run: python saga_checker.py
